//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Mark Mark { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Prepod Prepod { get; set; }
        public virtual Student Student { get; set; }
    }
}
